### ISSUE TITLE
A lot of image's size and position issues

### ISSUE THREAD

**Issue by AndyNotfound** [AndyNotfound/portfolio#1]
It occured at the footer section, recent projects section, about me section, and other section as well

![Image](https://user-images.githubusercontent.com/40969170/229509066-0212c7f2-688b-468e-a2ad-8e794768faa7.png)

![Image](https://user-images.githubusercontent.com/40969170/229509263-eedd0693-7657-4de3-94f8-8f15a42a10a3.png)

**Comment by sanchitpasricha** [comment]
Can you assign this issue to me, I can try.

**Comment by AndyNotfound** [comment]
Sorry man, but it has been fixed a long time ago, I just want to make an issue to fool around

**Comment by AndyNotfound** [comment]
you can try to fix the carousel issue if you want to, I'm skipping it to design the projects page, it's not really that hard to do anyway
